//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedFox.Core
{
    using System;
    
    public enum ExtensionType : int
    {
        Consumer = 100,
        Transcriber = 200,
        Converter = 300,
        Provider = 400,
        MessageClient = 700,
        NotificationTarget = 800,
        Recorder = 500
    }
}
