//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedFox.Core
{
    using System;
    
    public enum ProtocolType : int
    {
        Unknown = 0,
        Telnet = 1,
        Serial = 2,
        Phone = 3
    }
}
