//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedFox.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Id { get; set; }
        public Nullable<int> ServerId { get; set; }
        public int RateId { get; set; }
        public int StationId { get; set; }
        public SessionState State { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int WordCount { get; set; }
        public Nullable<System.DateTime> Schedule { get; set; }
        public int EncoderId { get; set; }
        public Nullable<int> Length { get; set; }
        public string CRON { get; set; }
        public bool Record { get; set; }
        public bool Muted { get; set; }
        public bool Paused { get; set; }
        public string Path { get; set; }
        public string ConsumerJson { get; set; }
        public string EncoderJson { get; set; }
        public string NotificationsJson { private get; set; }
    
        public virtual Rate Rate { get; set; }
        public virtual Server Server { get; set; }
        public virtual Station Station { get; set; }
        public virtual Encoder Encoder { get; set; }
    }
}
